### ISSUE TITLE
Missing Files running inference scripts.

### ISSUE THREAD

**Issue by RewindL** [nicolaus-huang/ProcessPainter#1]
Hello, when i run scripts for Painting Characters:
`python scripts/animate.py --config configs/prompts/character.yaml `
it comes with `No such file or directory: 'models/Motion_with_LoRA/character.ckpt'`
the same thing occurs when running:
`python scripts/animate.py --config configs/prompts/speedpainting.yaml`
and get ` No such file or directory: "models/DreamBooth_LoRA/revAnimated_v2Rebirth.safetensors"`

where should i get those file, or i missed something to do? Thanks.

**Comment by nicolaus-huang** [comment]
Hi, sorry for the inconvicence, for the first question, you can find it here https://huggingface.co/nicolaus-huang/ProcessPainter, we just updated the code recently. 

For the second problem, I think we just forgot to attach some pre-trained ckpt which comes from the community. You can find it in https://comfy.icu/files/revAnimated_v2Rebirth.safetensors.

Sorry again for the inconvience we have caused, we would update the readme correspondingly later.

**Comment by RewindL** [comment]
> Hi, sorry for the inconvicence, for the first question, you can find it here https://huggingface.co/nicolaus-huang/ProcessPainter, we just updated the code recently.
> 
> For the second problem, I think we just forgot to attach some pre-trained ckpt which comes from the community. You can find it in https://comfy.icu/files/revAnimated_v2Rebirth.safetensors.
> 
> Sorry again for the inconvience we have caused, we would update the readme correspondingly later.

That helps me. Thanks again for your reply.
