### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by louis062** [nicolaus-huang/ProcessPainter#2]
python scripts/animate.py --config configs/prompts/style2-cn-final.yaml 

FileNotFoundError: [Errno 2] No such file or directory: 'F:\\CodeEdit\\AI\\03_Paint\\ProcessPainter\\data\\test_frames\\0\\7.jpg'

Could you please share the image resources with me?  I just need ”data/test_frames/0……49“..

**Comment by nicolaus-huang** [comment]
Hi, that's  just random pictures for testing the model performance, however, you can now find them at https://huggingface.co/nicolaus-huang/ProcessPainter/tree/main/test.
