### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kmp1001** [nicolaus-huang/ProcessPainter#4]
hello，I noticed that the contents of the models\Motion_with_LoRA\adapter_config.json file is not in a valid JSON format: the file content you provided is not in the standard JSON format, but a Git LFS file. I cannot use Git. Can you provide the actual JSON file directly?

**Comment by nicolaus-huang** [comment]
updated, sorry for the misleading file
